### ISSUE TITLE
I can't build the table with ajax

### ISSUE THREAD

**Issue by captaincode0** [Holt59/datatable#25] opened 2017-07-06 23:41 UTC
I was doing a simple form with a table, it consists in the following i create a button to load more rows and avoid DOM overload or too much load to the page, but i generate the rows and when i want to filter data or change the page size, my content is erased.

In your documentation you tell that if i want to build the table with HTML, then i need to set * **data:** undefined||false*, but this doesn't work.

Note: I build my HTML content with one request to my API.

Have you an idea about what is the problem?

**Comment by Holt59** [comment] 2017-07-07 08:42
If you set:

```js
data: false
```

The plugin will use the current row of the table as its data, but it will not "link" the table to the data, in particular this means that:

- you cannot add element to the datatable using DOM manipulator;
- any content added to the table will be erased at the next `refresh()` of the table since the plugin completely re-draw the table at each `refresh()`.

You have multiple possibilities to bypass this:

1. create the datatable after loading the data, i.e. something like - best option if what you retrieve using the API is a HTML table:

```js
var data = get_data(...); // Your API call
$('#my-table').html(data);
$('#my-table').datatable();
```

2. create the datatable using the data retrieved from the API - good option if what you retrieve using the API is a JSON array:

```js
var data = get_data(...); // Your API call
$('#my-table').datatable({
    data: data
});
```

3. create the datable using an empty HTML table, then add row using `insert`:

```js
$('#my-table').datatable();
var data = get_data(...); // Your API call
$('#my-table').datatable('insert', data);
``` 

4. use the AJAX mode for loading data:

```js
{
    data: {
        url: "http://site.com/get", // The service URL
        type: "get",                // The type of request (post or get)
        size: null | int,           // Number of entries (or null for async. calls)
        allInOne: true,             // Set to true to load all your data in one AJAX call
        refresh: false              // You do not want a refresh
    }
}
```

I cannot tell you which one is the best for your case, but feel free to ask if you want more details about these.

**Comment by captaincode0** [comment] 2017-07-10 04:37
**Hi, Holt59**

I am really happy with your answer, and I am going to check my code and i'll figure out what's going on, but you gave me the next steep, thanks a lot.

Regards.

**Comment by anikettiwari009** [comment] 2017-07-27 07:29
i am new to jquery and i wanted know how can i set the offset and limit values in ajax url

**Comment by Holt59** [comment] 2017-07-27 08:53
@anikettiwari009 You cannot customize these options, these are automatically deduced from the `pageSize` and `pagingNumberOfPages` options. What are you trying to do exactly to have to customize these?

**Comment by captaincode0** [comment] 2017-07-27 21:00
Well @anikettiwari009 , i did the following.

I improve my tables with more code to set one offset and insert new data into my table, the steps that i follow:

1. Create one constructor to request to your table
```js
function AjaxTableCreator(){
this.offset = 10; //load 10 rows when you click one button
this.initial_limit  = 0;
this.final_limit = this.offset;
}

AjaxTableCreator.prototype.moveForwards = function(){
  this.initial_limit += this.offset;
  this.final_limit = this.offset+this.initial_limit;
}

AjaxTableCreator.prototype.build(){
   //make your ajax request with jquery
   $.getJSON(url, {start:this.initial_limit, end:this.final_limit}, function(data){
        $("#my-table").datatable("insert", data); //insert your data with the format specified in documentation
   });
}

var table_maker = new AjaxTableCreator();
```
2. You need to add one EventListener to your button with jQuery.
```js
$(document).ready(function(){
   $("#mybutton").click(function(){
      table_maker.moveForwards();
      table_maker.build();
   });
});
```

Regards, i did something like that with datatable plugin, thanks to @Holt59

**Comment by Holt59** [comment] 2017-12-14 14:24
Closing this issue since it looks like the problem is solved. Feel free to open a new issue if necessary.

**Closed by Holt59** 2017-12-14 14:24 UTC
