### ISSUE TITLE
t[o].cells[n] is undefined

### ISSUE THREAD

**Issue by NestorAcevedo** [Holt59/datatable#23] opened 2017-05-02 17:27 UTC
Hi, I have downloaded and I am implementing this plugin on a table with dynamic loaded rows from PHP but I am getting this error: `t[o].cells[n] is undefined` 

I have initialized the datatable with `$('#my-table').datatable({
            pageSize: 10
        });`

Do I am forgetting something?

**Comment by Holt59** [comment] 2017-05-02 17:44
How do you load the rows?

**Comment by NestorAcevedo** [comment] 2017-05-02 18:14
I load an array of objects. I "render" a view. In this view, I iter this array with a foreach, creating a row on each iteration:
`
<?php
?>
	      <tr style="color: black;">
		  <td><?= $object->id ?></td>
		  <td>
		      <?php
		      if ($object->user->first_name !== null) {
			  echo $object->user->first_name . " " . $object->user->last_name;
		      } else {
			  echo "Sin Asignar";
		      }
		      ?>
		  </td>
		  <td>
		      <?php
		      echo date("d M Y H:i:s", strtotime($object->date));
		      ?>
		  </td>
		  <td><?= "$object->distance Km" ?></td>
		  <td>
		      <?php
		      setlocale(LC_MONETARY, 'es_CO');
		      if (function_exists("money_format")) {
			  echo money_format("%.0n", $object->total);
		      } else {
			  $fmt = new NumberFormatter('es_CO', NumberFormatter::CURRENCY);
			  echo $fmt->formatCurrency($object->total, "COP");
		      }
		      ?>
		  </td>
	      </tr>
	      
	  `
this last one row is out of the foreach and will show only an info:
`<tr style="color: black;">
	      <td colspan=3"">&nbsp;</td>
	      <td><strong>Total:</strong></td>
	      <td>
		  <?php
		  setlocale(LC_MONETARY, 'es_CO');
		  if (function_exists("money_format")) {
		      echo money_format("%.0n", $total);
		  } else {
		      $fmt = new NumberFormatter('es_CO', NumberFormatter::CURRENCY);
		      echo $fmt->formatCurrency($total, "COP");
		  }
		  ?>
	      </td>
	  </tr>`

I apologize but the content is not loading all: the line for the foreach is not loaded but looks like: `foreach($objects as $object):`

**Comment by Holt59** [comment] 2017-05-02 18:18
I thought you were loading data with AJAX, which you are not. Could you use the non-compressed file (without `.min`) and show the error you get? Could you also show me the HTML table you get before using datatable (with pastebin or a gisthub)?

**Comment by NestorAcevedo** [comment] 2017-05-02 18:33
[https://pastebin.com/4a2TumV5](url)

> TypeError: rows[i].cells[j] is undefined  datatable.js:135:17

Table structure validated without errors

All is made with a custom WP Plugin

**Comment by Holt59** [comment] 2017-05-02 18:37
I think the problem is the footer - The plugin is currently not really made to work with non-data rows unfortunately.

Could you try without the footer and see what you get?

**Comment by NestorAcevedo** [comment] 2017-05-02 18:49
Yes, you are right. I closed the table before the last one row, and this last one was put onto a new table and finally I could see the pagination and the table rows are showed as expected.

Thank you so much :)

**Comment by Holt59** [comment] 2017-05-02 18:52
The plugin actually recreates the table each time you do operations on it (changing page, filtering, sorting, etc.), so you cannot add extra row in the table. However, using the `afterRefresh` option you should be able to add your footer, e.g.:

    $('#my-table').datatable({ 
        pageSize: 10,
        afterRefresh: function () {
            $(this).append(myFooter); // Where myFooter is whatever you want
        }
    });

**Comment by Holt59** [comment] 2017-05-02 19:02
Okay, this currently **does not** work, but this is not expected, so I am going to fix this ASAP so you can have a footer on your table!

**Comment by Holt59** [comment] 2017-05-02 19:14
@NestorAcevedo This should be fixed with latest commit so you can add a `tfooter` and it will stay in place when the table is refreshed (tested with your table).

**Comment by NestorAcevedo** [comment] 2017-05-02 19:17
Ah ok, so if I put a tfooter it should work. I will do. Again, thank you and don't worry, is working. this last one will be a new feature and a great improvement for your plugin that many of us will thank :)

**Closed** 2017-06-09 12:22 UTC
